### ISSUE TITLE
Package for Node 20

### ISSUE THREAD

**Issue by jp7837** [AArnott/Node.js.redist#9]
The current LTS version of Node is v20.9.0. Please could you upload a Nuget for this version? Thank you!

**Comment by AArnott** [comment]
Pushing to nuget.org is blocked because the package is too big. I don't know if node.js got bigger, or nuget.org introduced or lowered a package size limit, but I'm blocked at this point.
One possible way forward: split the package up by OS so one package doesn't have to contain 5 copies of node.js.

**Comment by AArnott** [comment]
Oh, I guess only the symbols package was rejected. So, at least the runtime package pushed. :)

**Comment by AArnott** [comment]
The symbols package split will be tracked by #10.
